<a href="https://colab.research.google.com/github/ramcharan2823/AI/blob/NLP_ML/Implementation_word_embedding_using_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## Libraries using keras and tensorflow 2.0

In [7]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [10]:
pip install tensorflow

In [11]:
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
#sentences
sent=['the glass of milk',
      'the glass of juice',
      'I am good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [14]:
### vocabulary size
voc_size = 10000

One Hot **Representation**


In [15]:
onehot_rep = [one_hot(words,voc_size)for words in sent]
print(onehot_rep)

[[7772, 6539, 6280, 1091], [7772, 6539, 6280, 4507], [2537, 6897, 9059, 416], [2537, 6897, 4297, 9059, 8761], [8552, 7772, 2978, 6280, 6877], [150, 1226, 7258, 9059]]


**Word Embedding Representation**

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [17]:
import numpy as np

In [18]:
sent_length=8
embedded_docs=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7772 6539 6280 1091]
 [   0    0    0    0 7772 6539 6280 4507]
 [   0    0    0    0 2537 6897 9059  416]
 [   0    0    0 2537 6897 4297 9059 8761]
 [   0    0    0 8552 7772 2978 6280 6877]
 [   0    0    0    0  150 1226 7258 9059]]


In [19]:
dim=15

In [20]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [21]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 240ms/step
[[[ 0.03587332  0.03524903 -0.04271482 -0.00494257 -0.01813107
    0.04694753 -0.0345781   0.01805128 -0.02212929 -0.03233387]
  [ 0.03587332  0.03524903 -0.04271482 -0.00494257 -0.01813107
    0.04694753 -0.0345781   0.01805128 -0.02212929 -0.03233387]
  [ 0.03587332  0.03524903 -0.04271482 -0.00494257 -0.01813107
    0.04694753 -0.0345781   0.01805128 -0.02212929 -0.03233387]
  [ 0.03587332  0.03524903 -0.04271482 -0.00494257 -0.01813107
    0.04694753 -0.0345781   0.01805128 -0.02212929 -0.03233387]
  [ 0.03104729  0.02821385 -0.00557476 -0.03067515  0.02381558
   -0.02052752 -0.02968247  0.04232962  0.02764112 -0.04211699]
  [-0.04412508  0.00194056  0.02482371 -0.01609055  0.00165975
   -0.03424859  0.03779489 -0.01584706  0.0034477  -0.00789361]
  [-0.02812093  0.04910235 -0.03438374 -0.02925521  0.03936001
   -0.00888594  0.04464624 -0.02085732  0.03276447  0.01167984]
  [ 0.02151285  0.02632935 -0.00979502 -0.03634451  0.04535237
   -0.049

In [23]:
embedded_docs[0]

array([   0,    0,    0,    0, 7772, 6539, 6280, 1091], dtype=int32)

In [24]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[[ 0.03587332  0.03524903 -0.04271482 -0.00494257 -0.01813107  0.04694753
  -0.0345781   0.01805128 -0.02212929 -0.03233387]
 [ 0.03587332  0.03524903 -0.04271482 -0.00494257 -0.01813107  0.04694753
  -0.0345781   0.01805128 -0.02212929 -0.03233387]
 [ 0.03587332  0.03524903 -0.04271482 -0.00494257 -0.01813107  0.04694753
  -0.0345781   0.01805128 -0.02212929 -0.03233387]
 [ 0.03587332  0.03524903 -0.04271482 -0.00494257 -0.01813107  0.04694753
  -0.0345781   0.01805128 -0.02212929 -0.03233387]
 [ 0.03104729  0.02821385 -0.00557476 -0.03067515  0.02381558 -0.02052752
  -0.02968247  0.04232962  0.02764112 -0.04211699]
 [-0.04412508  0.00194056  0.02482371 -0.01609055  0.00165975 -0.03424859
   0.03779489 -0.01584706  0.0034477  -0.00789361]
 [-0.02812093  0.04910235 -0.03438374 -0.02925521  0.03936001 -0.00888594
   0.04464624 -0.02085732  0.03276447  0.01167984]
 [ 0.02151285  0.02632935 -0.00979502 -0.03634451  0.04535237 -0.04938405
   0.0316201 